package view;

import bean.Bean;
import controller.ChangeScreenController;
import java.util.ArrayList;
import java.util.List;

public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("Personal Finance Management");
        
        ChangeScreenController controller = new ChangeScreenController(jpnView);
        controller.setView(jpnHome, jlbHome);
        
        List<Bean> listItem = new ArrayList<>();
        listItem.add(new Bean("Home",jpnHome,jlbHome));
        listItem.add(new Bean("Transaction",jpnTransaction,jlbTransaction));
        listItem.add(new Bean("NewExpense",jpnNewExpense,jlbNewExpense));
        listItem.add(new Bean("Income",jpnIncome,jlbIncome));
        listItem.add(new Bean("Report",jpnReport,jlbReport));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnHome = new javax.swing.JPanel();
        jlbHome = new javax.swing.JLabel();
        jpnNewExpense = new javax.swing.JPanel();
        jlbNewExpense = new javax.swing.JLabel();
        jpnTransaction = new javax.swing.JPanel();
        jlbTransaction = new javax.swing.JLabel();
        jpnIncome = new javax.swing.JPanel();
        jlbIncome = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpnReport = new javax.swing.JPanel();
        jlbReport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpnMenu.setBackground(new java.awt.Color(0, 153, 153));

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/currency_exchange_20dp_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jLabel1.setText("Personal Finance");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jpnHome.setBackground(new java.awt.Color(255, 153, 51));

        jlbHome.setBackground(new java.awt.Color(204, 255, 255));
        jlbHome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbHome.setForeground(new java.awt.Color(204, 255, 255));
        jlbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_white_24dp.png"))); // NOI18N
        jlbHome.setText("Home");

        javax.swing.GroupLayout jpnHomeLayout = new javax.swing.GroupLayout(jpnHome);
        jpnHome.setLayout(jpnHomeLayout);
        jpnHomeLayout.setHorizontalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnHomeLayout.setVerticalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbHome)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpnNewExpense.setBackground(new java.awt.Color(255, 153, 51));

        jlbNewExpense.setBackground(new java.awt.Color(204, 255, 255));
        jlbNewExpense.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbNewExpense.setForeground(new java.awt.Color(204, 255, 255));
        jlbNewExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add expense.png"))); // NOI18N
        jlbNewExpense.setText("New expense");

        javax.swing.GroupLayout jpnNewExpenseLayout = new javax.swing.GroupLayout(jpnNewExpense);
        jpnNewExpense.setLayout(jpnNewExpenseLayout);
        jpnNewExpenseLayout.setHorizontalGroup(
            jpnNewExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNewExpenseLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNewExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpnNewExpenseLayout.setVerticalGroup(
            jpnNewExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNewExpenseLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNewExpense)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnTransaction.setBackground(new java.awt.Color(255, 153, 51));

        jlbTransaction.setBackground(new java.awt.Color(204, 255, 255));
        jlbTransaction.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbTransaction.setForeground(new java.awt.Color(204, 255, 255));
        jlbTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transaction.png"))); // NOI18N
        jlbTransaction.setText("Transaction");

        javax.swing.GroupLayout jpnTransactionLayout = new javax.swing.GroupLayout(jpnTransaction);
        jpnTransaction.setLayout(jpnTransactionLayout);
        jpnTransactionLayout.setHorizontalGroup(
            jpnTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTransactionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTransactionLayout.setVerticalGroup(
            jpnTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTransactionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTransaction)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpnIncome.setBackground(new java.awt.Color(255, 153, 51));

        jlbIncome.setBackground(new java.awt.Color(204, 255, 255));
        jlbIncome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbIncome.setForeground(new java.awt.Color(204, 255, 255));
        jlbIncome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paid_white_24dp.png"))); // NOI18N
        jlbIncome.setText("Income");

        javax.swing.GroupLayout jpnIncomeLayout = new javax.swing.GroupLayout(jpnIncome);
        jpnIncome.setLayout(jpnIncomeLayout);
        jpnIncomeLayout.setHorizontalGroup(
            jpnIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIncomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jpnIncomeLayout.setVerticalGroup(
            jpnIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnIncomeLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jlbIncome)
                .addGap(15, 15, 15))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Custom by Minh Hiển");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jpnReport.setBackground(new java.awt.Color(255, 153, 51));

        jlbReport.setBackground(new java.awt.Color(204, 255, 255));
        jlbReport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbReport.setForeground(new java.awt.Color(204, 255, 255));
        jlbReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jlbReport.setText("Investment");

        javax.swing.GroupLayout jpnReportLayout = new javax.swing.GroupLayout(jpnReport);
        jpnReport.setLayout(jpnReportLayout);
        jpnReportLayout.setHorizontalGroup(
            jpnReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReportLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbReport, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnReportLayout.setVerticalGroup(
            jpnReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReportLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlbReport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnMenuLayout.createSequentialGroup()
                        .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jpnNewExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpnTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jpnIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jpnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnNewExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbHome;
    private javax.swing.JLabel jlbIncome;
    private javax.swing.JLabel jlbNewExpense;
    private javax.swing.JLabel jlbReport;
    private javax.swing.JLabel jlbTransaction;
    private javax.swing.JPanel jpnHome;
    private javax.swing.JPanel jpnIncome;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNewExpense;
    private javax.swing.JPanel jpnReport;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTransaction;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}